### ISSUE TITLE
Adding COINS or ZOTERO connectivity? Create a citation?

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#111]
@wsalesky , we'd like to enable users to pull the data pull citations for individual works into their reference tools, like Zotero. I'm not sure what the best way to do this is--if anything needs to go into the XML itself? We have the data, though, in the TEIHeader/sourceDesc, to make a citation, that in MLA form would look like this:

sourceDesc//monogr/author/surname, monogr/author/firstname. "analytic/title." (if analytic exists) <hi rend="italic">monogr/title</hi>, monogr/publisher (first refc'd), monogr/date (first refc'd), monogr/biblScope (if exists). <hi rend="italic">Literature in Context: An Open Anthology</hi>. permalink url. Accessed: todays date.

**Comment by wsalesky** [comment]
@tonyahowe I will look into it.

**Comment by wsalesky** [comment]
I have added COinS and also a citation to each work page. 
<img width="1248" alt="Screen Shot 2020-04-01 at 12 48 20 PM" src="https://user-images.githubusercontent.com/1168206/78164056-2f02bd80-7417-11ea-92f5-61fde8b3e691.png">


Reopen if there are any issues, or changes you would like to see.
