### ISSUE TITLE
Contributor name in annotation

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#12]
Can we display the name of the author of the annotation somehow? Pulled from @resp=”editors.xml#AF”? Probably in brackets at the end of the annotation, like this [Ally Freeland] or [AF]

Could that included contributor info become a link to their section in the contributors/editors page? See editors/contributors #4 below!

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 
Done. Close after review.

**Comment by tonyahowe** [comment]
Thanks, Winona!
