### ISSUE TITLE
Tooltips in coursepacks

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#129]
Some users seem to be having difficulty with the two link options in coursepacks, especially when it comes to selections that have been added. 

The + button has a tooltip that reads "click to expand text" and the title of the text is also a link (but no tooltip). Is it possible to alter the tooltips on both the + and the title of the text to read as follows:

+ Plus Sign --> "click to expand coursepack selection"
+ Title --> "click to go to full text"

<img width="935" alt="Screen Shot 2021-08-18 at 1 19 32 PM" src="https://user-images.githubusercontent.com/1153464/129943810-11168946-c5c3-4d42-8135-567bb6d4d412.png">

**Comment by tonyahowe** [comment]
This looks great! One problem: there's a typo in the tool tip
<img width="371" alt="Screen Shot 2022-10-14 at 9 52 10 AM" src="https://user-images.githubusercontent.com/1153464/195864682-d066aaef-935e-4504-845a-63b686f0b36d.png">

**Comment by wsalesky** [comment]
Opps! Sorry about that. Corrected.
