### ISSUE TITLE
Work toolbar

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#13]
Really love the expanding items at the top of the text display page to toggle “sources” and “notes”! Can we rename to “Source Texts” and “Editorial Statements”?

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62  Done. Close on review.

**Comment by jobrien62** [comment]
I like it, but we might just need "Editorial Statement" (when it reads "statements" I was looking for something else to click on to get a second, third, fourth statement, etc.

**Comment by tonyahowe** [comment]
@jobrien62 I was imagining the individual editorial components as referenced in the teiHeader--the normalization statement, the research statement, and so on. I wonder if it will confuse others? Perhaps something to ask our outside readers, too!
