### ISSUE TITLE
Login functionality

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#136]
I think I figured it out--the login does not work if you select "remember me for 2 weeks". See video attached.

https://user-images.githubusercontent.com/1153464/190694329-7d410f32-9d6c-4327-afd2-2ff198667948.mov

**Comment by wsalesky** [comment]
@tonyahowe Can you test now? I have updated this functionality.

**Comment by tonyahowe** [comment]
Fixed!
