### ISSUE TITLE
Deleting coursepacks

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#138]
Coursepacks seem not able to be deleted by the associated user (or by admin). See video below.

https://user-images.githubusercontent.com/1153464/190696528-a23f6583-e5ca-4ea3-ae41-65a4499d86bb.mov

https://user-images.githubusercontent.com/1153464/190696589-a9728544-f2f2-4b8f-9361-7a903d9cf0cc.mov

**Comment by wsalesky** [comment]
@tonyahowe Can you test this now? I was able to create a new user, create and delete a coursepack.

**Comment by tonyahowe** [comment]
I logged in as thowe and couldn't delete the dated test coursepack. I'm using the Brave browser.

**Comment by tonyahowe** [comment]
I can delete items in the coursepack, but not the coursepack itself.

**Comment by wsalesky** [comment]
Okay, I will take a look.

**Comment by wsalesky** [comment]
@tonyahowe Can you try now. Create a few new coursepacks, try to delete your own, and then try to delete yours when logged in as admin.

**Comment by wsalesky** [comment]
@tonyahowe any updates? Is this working for you?

**Comment by tonyahowe** [comment]
Okay, I CAN delete a coursepack made by user thowe as admin, but as thowe, I cannot delete a coursepack made by thowe. See video

https://user-images.githubusercontent.com/1153464/194073957-3554aa3e-3718-4f00-be44-749690c35c6b.mov

**Comment by wsalesky** [comment]
@tonyahowe may be the same issue as: https://github.com/LiteratureInContext/LiC-app/issues/147
Please try now.

**Comment by tonyahowe** [comment]
Still can't seem to delete as thowe; see video!

https://user-images.githubusercontent.com/1153464/194653469-7f08eabb-409a-457d-bc9c-d6d1986c3bf9.mov

**Comment by wsalesky** [comment]
@tonyahowe I think this can be closed?
