### ISSUE TITLE
Print/screen displays

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#14]
Can we add different displays for screen reading and for printing? In the screen reading options (viewing an expanded coursepack or reading a single text), notes should be displayed in line, but for printing/PDF, they should be footnotedn001 and displayed at the bottom of each page.

**Comment by jobrien62** [comment]
This would be pretty awesome. We had spoken of this, I think, on a conference call a while back, with the idea that when reading in-line, the notes would appear as highlighted or differently colored texts, with the pdf version then having more conventional numerical notes, tied to footnotes. If this is possible, fantastic.

**Comment by tonyahowe** [comment]
This is definitely a great enhancement.

**Comment by wsalesky** [comment]
@jobrien62 @tonyahowe Just to clarify, for the screen you would like the text with the `tei:ref` highlighted or in different color, do you want the footnote numbers as superscript as well, or should those be hidden? Currently the page looks like this: 
<img width="1104" alt="Screen Shot 2019-03-17 at 12 07 36 PM" src="https://user-images.githubusercontent.com/1168206/54494123-71f5ff80-48ad-11e9-8611-49fd2510d32a.png">

**Comment by tonyahowe** [comment]
Yes! I believe the idea was to show them as underlined links for screen reading (viewing each text or the coursepack), but visible note numbers for more traditional print reading (the coursepack pdf, and the print individual texts).

**Comment by jobrien62** [comment]
Yes, that’s the idea. 

I was able to get the pdf option to work great, by the way, on Pope, which I did some work on last night. John

**Comment by wsalesky** [comment]
@jobrien62 @tonyahowe This has been added. See: 
https://anthologydev.lib.virginia.edu/work/Bradstreet/bradstreet-childhood
as an example.  You may close this if it looks good.

**Comment by jobrien62** [comment]
It doesn't quite work yet. On the web, the note number pops up, but not the note itself, at least when I try, on this example and on others.

**Comment by wsalesky** [comment]
Ops. Sorry bug in the javascript. Should work now.

**Comment by tonyahowe** [comment]
Wonderful--thank you! In the future we'd probably like to make some changes to the way the PDF looks, like removing the underlining, adding authors and pub details in the TOC, and so on. But I think we can close this for now! 👍
