### ISSUE TITLE
Labeling in Coursepack creation

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#144]
When I add an item to a new coursepack, after searching, I have only the option (seemingly) to add to an existing coursepack. Clicking that then allows you to add to a new coursepack. Perhaps removing the "existing" from the button label here and wherever else? See screenshot:
![Screen Shot 2022-10-05 at 9 17 29 AM](https://user-images.githubusercontent.com/1153464/194070211-01cf9e44-efff-4530-bcea-9af927adc906.png)

**Comment by tonyahowe** [comment]
Ah-- It's in the tooltip that pops up, not the button itself:
<img width="817" alt="Screen Shot 2022-10-05 at 9 24 38 AM" src="https://user-images.githubusercontent.com/1153464/194071502-0e35b1fd-6073-4ecf-ae12-7bb55305c0fb.png">

**Comment by tonyahowe** [comment]
On a related note, on this same page there is a search button/magnifying glass that doesn't seem to do anything?
![Screen Shot 2022-10-05 at 9 26 47 AM](https://user-images.githubusercontent.com/1153464/194071920-dcacc30c-5901-443d-95fd-29d6eeeee235.png)

**Comment by wsalesky** [comment]
@tonyahowe which one? The one followed by new, clears or 'resets' you search, taking you back to the full list of titles. The other one, near the search box, submits the search string.

**Comment by wsalesky** [comment]
text in tool tip is fixed.
