### ISSUE TITLE
Saving selections to existing coursepacks

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#145]
Having a problem saving selections to coursepacks. Also note need to log in again (which is less of a problem than the saving!):

https://user-images.githubusercontent.com/1153464/194076963-1619766d-672a-410b-8a7a-bbc4c616bed3.mov

**Comment by wsalesky** [comment]
This is most likely the same as https://github.com/LiteratureInContext/LiC-app/issues/147

Try now, should be resolved.

**Comment by tonyahowe** [comment]
Don't seem able to do this, either, yet; see video


https://user-images.githubusercontent.com/1153464/194657556-c9279698-6ec7-4bed-bb01-b5aa14b2a2bc.mov

**Comment by tonyahowe** [comment]
However, I can save selections as admin:


https://user-images.githubusercontent.com/1153464/194658505-5a6c8f2f-3924-4969-97d2-cd3f2a764a30.mov

**Comment by wsalesky** [comment]
@tonyahowe okay. There is clearly some sort of permissions mismatch between the dev server and my test server. I will see what I can do to work it out.

**Comment by wsalesky** [comment]
Can you do any of these if you create a new user? (Just trying to figure out where the permission issue is)

**Comment by tonyahowe** [comment]
Okay, i's very weird. When I create a coursepack as a new user (test, test1), that works--I have that first selection in the new coursepack. But when I try to add anything to that coursepack (selection or whole text), it doesn't save.

**Comment by wsalesky** [comment]
Okay, this time I really think I have it. Please try:
1. creating a new user
2.  creating a coursepack,
3.  logging out, 
4. logging back in, 
5. deleting items in coursepack
6. adding new items
7. adding new selections
8. deleting the whole coursepack

I did all of this with a new user on the dev site. So you should be able to as well. We may have to do some adjustements for the permissions on any already created coursepacks in order to be able to edit them.

**Comment by tonyahowe** [comment]
Yes, it all works!! I uncovered a new problem though. I'll send you the screencast via email, but basically sometimes when I search (specifically, for "lady susan"), I get a 500 server error (and it also threw a jetty error when I searched for "lady susan: inadvertently).

**Comment by wsalesky** [comment]
@tonyahowe I opened a new issue for the search problem. Can I close this one?

**Comment by tonyahowe** [comment]
I think so—I opened another issue for the selection problem. I didn’t notice it before because I was just checking to see if there were items saving to the coursepack, which there were. It turns out that the content wasn’t actually selected though.

**Comment by wsalesky** [comment]
@tonyahowe I just tested the saving a selection and it worked for me. See: https://anthologydev.lib.virginia.edu/coursepack/WSTestselection.5

Could you have to use the 'expand' button to see the selected text. Clicking on the title takes you to the work. This may be a user interface issue, not a javascript issue. Can you just test the selection function again and confirm that you can save a selection? Then we can discuss how to make the different functions with in the coursepack more clear to the user. 

Thanks!

**Comment by tonyahowe** [comment]
Yes, this works--thanks! It also saves multiple selections from the same text. Some things to consider as signage for users:

1.) tooltip or title on "expand works"--clarifying there? "expand works to see selections"?
2.) turn the word "selections from" into a link that expands?
3.) change the text "selected text" heading each selection to "selected text [number if more than one selection from same text] from [title]"--so, "selected text 1 from Robinson Crusoe...." or, if only 1 selection from the text, "selected text from Robinson Crusoe..."?

**Comment by wsalesky** [comment]
Yay! I am going to close this and open a new issue for the coursepack usability. I will add your comments to that issue.
