### ISSUE TITLE
Add endnote

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#15]
Could we also add endnote display as an option for printing/saving to PDF?

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 
Are you aware of any sites that describe the endnote format that I can use to add this output? Or is there an API?

**Comment by tonyahowe** [comment]
I think we're thinking of the endnote as just like the footnote, but placed at the end of the printable file instead of at the bottom of each page. This is related to #14 -- multiple ways to engage with the reading of the text. @jobrien62 does that make sense?

**Comment by wsalesky** [comment]
Can you give me an example, pick a work and mock up how you would like it to appear? Thanks!

**Comment by tonyahowe** [comment]
I think what you've done works well, especially for now! 👍
