### ISSUE TITLE
Delete 9/12/22 Coursepack

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#150]
It seems to be impossible to delete the 9/12/22 coursepack--the title has forward slashes in it, which get confused with the URL structure. Can you delete this coursepack at the source? And we will need (sometime in the nearish future) some rails on the titling of the coursepacks so this doesn't happen in the future! :)

**Comment by wsalesky** [comment]
@tonyahowe I will delete it and add a script to strip the slashes from filenames.

**Comment by wsalesky** [comment]
Okay I think this has been resolved.
