### ISSUE TITLE
Important: Save selections saving whole text?

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#151]
It looks like the save selection feature is actually saving the whole text, not just the highlighted selection--though the coursepack lists the material as "selections." 

https://user-images.githubusercontent.com/1153464/194959161-6d1be160-b1d2-4a11-93d5-a739a5e84e28.mov

**Comment by wsalesky** [comment]
see comment here: https://github.com/LiteratureInContext/LiC-app/issues/145

**Comment by wsalesky** [comment]
@tonyahowe Closing this as it is the same as #145, and I'm getting confused with both open. ;)
