### ISSUE TITLE
Searching with quotes causes 500 error

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#152]
> Yes, it all works!! I uncovered a new problem though. I'll send you the screencast via email, but basically sometimes when I search (specifically, for "lady susan"), I get a 500 server error (and it also threw a jetty error when I searched for "lady susan: inadvertently).

https://github.com/LiteratureInContext/LiC-app/issues/145

**Comment by wsalesky** [comment]
Clarification to myself, this is not related to quotes. 
This search works: 
https://anthologydev.lib.virginia.edu/search.html?query=%22world+to+himself%22&field=keyword

This does not: 
https://anthologydev.lib.virginia.edu/search.html?query=%22lady+susan%22&field=keyword

Maybe some sort of index corruption?

**Comment by wsalesky** [comment]
@wsalesky Note to self: 
This happens on my local version as well, only for "lady susan" on a keyword search, no other keyword searches with quotes have generated this error. 

Error generated by search: 
HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/LiC/search.html: An unknown error occurred: String index out of range: -364

**Comment by tonyahowe** [comment]
This is soooo weird!

**Comment by wsalesky** [comment]
It really is. Let me know if you find any other search that kicks up that error, so far it is only for lady susan, in quotes.

**Comment by wsalesky** [comment]
@tonyahowe This no longer happens on the dev server, which we had to re boot. It still happens on the production server, so I think it is a corrupted data issue. It should resolve once we successfully restore the production server from backup. Hopefully we can do it this week. I want to make sure we have a full backup though.
