### ISSUE TITLE
Line Numbers

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#161]
The line numbers are posing some interesting problems, especially in longer texts (like Shakespeare's Tempest). It's just very overwhelming to have each line numbered and the numbers appearing at the beginning. I am not quite sure what the solution is, but in an ideal world, we'd prefer to:

1. Show line numbers for every 5 lines (that is, only show the numbers at 5, 10, 15, etc)
2. Put the line numbers at the end of the lines, perhaps in [brackets] to distinguish them--or right-align them, though I'm not sure how this would be accomplished given different line sizes and the fact that we don't want overlaps. 

This would be duplicated in the PDF and EPUBs formats.

**Comment by wsalesky** [comment]
This should be fixed. Close if you are satisfied.

**Comment by tonyahowe** [comment]
The PDF looks great! The ePUB now doesn't render line breaks, but the line numbers are at the end. Can we do the same for the regular view website? That is, line numbers on all with line numbers in increments of 5 to the right?
<img width="1138" alt="Screen Shot 2022-11-14 at 1 46 08 PM" src="https://user-images.githubusercontent.com/1153464/201741010-f9383739-6e69-42e6-81b0-b1518ae693fe.png">

**Comment by wsalesky** [comment]
@tonyahowe Can you send me a screen shot of the epub issue? And a link to the test record. 
Thanks! (Also, yes, I can make the change to the HTML view as well. )

**Comment by wsalesky** [comment]
I added this to the HTML view.

For the ePUB, I found the error you mentioned when opening the file in ibooks on my macbook. It looks like it is not reading the css file. I will troubleshoot. Please let me know if you are using a different app to open the epub files, I want to test on multiple platforms. It works nicely in the Firefox epub extension.

**Comment by wsalesky** [comment]
@tonyahowe This fixed the issue for me. How does it look for you?
