### ISSUE TITLE
XSLT/Formatting for authorship in browse

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#172]
It seems that the author as noted in the browse lists is drawn from biblStruct / monogr in the TEI header, and the author as noted in the byline on the actual text page is drawn from titleStmt.... Is that correct? 

I am testing with poe-tell-tale.xml.

There may be times (quite likely) when an analytic text comes from a monogr that doesn't have an author (for instance, a magazine). We need authorship to always be associated with the author in the analytic. Right now, it doesn't seem that my schema lets me add an author to the analytic, but I must have one in the monogr. **What I'd like to do is require an author in the analytic, and make authorship in the mongr optional. Authorship for browse display should be populated from authorship in analytic IF there is no author in monogr. BUT, if there is no analytic, and only authorship in monogr, then authorship should be populated from monogr.**

In addition, see the note on second forenames in issue #173 . I'm working right now with two authors who both have 3 names, but none of those names are "addNames," as in the case of John Wilmot, Earl of Rochester. Instead, these are authors like Thomas Sterns Eliot and Edgar Allan Poe. It's convention to refer to them with three names, not two (as in Thomas Eliot or Edgar Poe).

This will mean I'll have to rework the xml in many cases, but it's more accurate.

**Comment by wsalesky** [comment]
@tonyahowe Just to make sure I have this right, all author displays should come from biblStruct/analytic, unless there is no analytic author, then they should be generated from biblStruct/monogr. They should never come from the titleStmt. Correct?

**Comment by tonyahowe** [comment]
Fabulous--thanks!
