### ISSUE TITLE
CP updates: delete, title restrictions, identify ownership

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#179]
We may need some naming conventions hard-wired into the app around coursepack titles; we cannot use / \ slashes or ( ) parentheses, it seems. Can you delete the coursepack  "Literature of the British Isles (Marymount University)"? We don't need to deal with the title restrictions just now, but it's on the horizon. It would also be nice if, when viewing CPs as admin, we could see authorship of each coursepack. 

Good news on the horizon, too! The last big grant we applied for was approved--more later!

**Comment by wsalesky** [comment]
Deleted. I can add some logic that strips problematic characters out of titles when saving. It is not a problem for the title, it is a problem for the filename, which is based on the title.

**Comment by wsalesky** [comment]
The filename issue should be resolved. Also in the future you can delete bad files via eXide if you are logged in as admin.
