### ISSUE TITLE
Editors/contributors

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#18]
New page for editors and contributors. 

We need a page (linked from the top nav structure) to editor/contributor information. 

On that page, can we have a list of all the editors/contributors identified in editors.xml? 

It would also be helpful to include counts for annotations contributed and texts contributed to, with links. Do you think the annotations should be displayed somehow, John and Chris? I think yes, somehow--not sure how best to do that, but some kind of toggle/expand/collapse situation around the word or phrase that’s been annotated? Like this: I think that this would work. I take it that this is easy (?) or at least that the xml can encode this and then exist-db can pull it fairly readily

Ally Freeland (32 annotations, 3 texts)
Frankenstein ➕➖
PROMETHEUS 
Did I request thee, Maker, from my clay To mould me man? Did I solicit thee From darkness to promote me?
PARADISE LOST.
Other text ➕➖
Other text ➕➖

See notes 2 & 3 from display, above, about indicating authorship of the annotations from the @resp=”editors.xml#AF” information.

**Comment by wsalesky** [comment]
@wsalesky @jobrien62 Added. Close if approve.

**Comment by jobrien62** [comment]
I think this works. How are we adding new contributors? I have some names to add; is there an easy way to add this information (now and going forward)?

**Comment by tonyahowe** [comment]
@jobrien62 We add details for contributors in editors.xml; then, reference them in the `<note>`s and the `<teiHeader>` as follows:

In `<teiHeader>`:
```
<editor>
                         <persName type="orcid" key="0000-0002-7400-4093">
                            <name ref="editors.xml#TH">
                               <forename>Tonya</forename> 
                               <surname>Howe</surname>
                            </name>
                         </persName>
                      </editor>
                      <respStmt>
                         <resp>Transcription, correction, editorial commentary, and markup</resp>
                         <name ref="editors.xml#MUstudstaff">Students of Marymount University</name>
                         <name ref="editors.xml#JW"><forename>James</forename> <surname>West</surname></name>
                         <name ref="editors.xml#AR"><forename>Amy</forename> <surname>Ridderhof</surname></name>
                      </respStmt>
```

And in `<note>s`:

```
<note xml:id="n005" target="a005" type="editorial" resp="editors.xml#JW"><p>According to <ref
                  target="http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0104%3Aalphabetic+letter%3DM%3Aentry+group%3D31%3Aentry%3Dmusae-bio-1"
                  ><hi rend="italic">A Dictionary of Greek and Roman Biography and
                     Mythology</hi></ref>, the Muses are "inspiring goddesses of song" who
                  "presid[e] over the different kinds of poetry, and over the arts and sciences." In
                  this poem, Finch positions the nightingale as her muse and rival. </p></note>
```

**Comment by wsalesky** [comment]
@jobrien62 @tonyahowe I think this can be closed.
