### ISSUE TITLE
Linked Data display for network graph (Collection Graph)

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#180]
Is it possible to make this graph zoomable, to fit better in the space? As the collection grows, we're seeing the invisible borders of the graph's rectangular space, created when nodes butt up agains the limits of the space.

**Comment by wsalesky** [comment]
Can you send a link and an image?

**Comment by tonyahowe** [comment]
<img width="2013" alt="Screen Shot 2023-01-06 at 11 50 59 AM" src="https://user-images.githubusercontent.com/1153464/211058920-d597ef98-ac6c-4709-ad55-6ebf48b618e8.png">

**Comment by tonyahowe** [comment]
Another request related to this one--not sure it should be in its own issue? Anyway, in the network graph (above), is it possible to highlight the edges and first-level connecting nodes extending from a selected node? So a user can see more clearly where the points of connection are.

**Comment by wsalesky** [comment]
@tonyahowe How does the updated version on the development site look now?

**Comment by tonyahowe** [comment]
Oh, it looks good! I have a few more requests re: the network graph, but I’ll have to post about them later. This is great for now, thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tonyahowe** [comment]
This is fantastic. I think anything else can wait!
