### ISSUE TITLE
LOD map not associating places with works

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#184]
In the production site, the LOD for places are wonky--clicking on the map shows "null" (and clicks to a 404 error) for the works associated with all locations: 

<img width="539" alt="Screen Shot 2023-04-10 at 6 57 03 PM" src="https://user-images.githubusercontent.com/1153464/231014576-b3a8b5b0-b1ad-42a3-b1be-9de1a3a5fe74.png">

**Comment by wsalesky** [comment]
@tonyahowe These run off of static index files that you will need to regenerate every once in a while. I will send an email on how to do that.
