### ISSUE TITLE
respStmt/resp updates

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#185]
Hi, Winona! Just *finally* getting around to uploading these issues. First one on my list, from a list in no particular order:

We need the ability to have more than one <resp> in the digital edition display. For instance--

```
			<respStmt>
					<resp>TEI encoding, formatting, and annotation integration</resp>
					<name ref="editors.xml#StudStaffUO">Students and Faculty at the University of Oregon</name>
					<name>Kathleen Gekiere</name>
					<name>Megan Hayes</name>
					<name>Honor O'Sullivan</name> 
					<name>Michele Pflug</name>
					<name ref="editors.xml#MB">Mattie Burkert</name>
					<resp>Composition and research of contextual annotations</resp>
					<name>Kaleb Beavers</name>
					<name>Matthew Bicakci</name>
					<name>Jessie Heine</name>
					<name>Kimberly Olivar</name>
					<resp>Definition of archaic and unfamiliar words</resp>
					<name>Annalise San Juan</name>
					<name>Ashia Ajani</name>
					<name>Rachel Peri</name>
					<resp>Retrieval and annotation of place and person name unique IDs</resp>
					<name>Josiah Basaldua</name>
					<name>Nikki Cain</name>
					<name>Rachel Comb</name>
					<resp>Page image integration</resp>
					<name ref="editors.xml#MB">Mattie Burkert</name>
				</respStmt>
```

Or, the ability to have more than one <respStmt>. Whichever seems more canonical we'd go with. Not many texts now have this level of descriptive detail, but we anticipate this becoming an issue. 

We'd like it to be rendered as follows in the location it's normally in: 

**Transcription, correction, editorial commentary, and markup by: Students and Faculty at the University of Oregon, Kathleen Gekiere, Megan Hayes, Honor O'Sullivan, Michele Pflug, and Mattie Burkert. Composition and research of contextual annotations by: Kaleb Beavers, Matthew Bicakci, Ashia Ajani, Jesse Heine, and Kimberly Olivar. Definition of archaic and unfamiliar words by: Annalise San Juan, Ashia Ajani, and Rachel Peri. Retrieval and annotation of place and person name unique IDs by: Josiah Basaldua, Nikki Cain, and Rachel Combs. Page image integration by: Mattie Burkert.**

Here is a file for reference: https://anthologydev.lib.virginia.edu/work/Winkfield/winkfield-female-american (it may not parse because the XML doesn't work. The old version is on the stable site!)

**Comment by wsalesky** [comment]
@tonyahowe I think this encoding makes more sense, and is easier to code for: 
```
<respStmt>
					<resp></resp>
					<resp>TEI encoding, formatting, and annotation integration</resp>
					<name ref="editors.xml#UOStudStaff">Students and Faculty at the University of Oregon</name>
					<name>Kathleen Gekiere</name>
					<name>Megan Hayes</name>
					<name>Honor O'Sullivan</name> 
					<name>Michele Pflug</name>
					<name ref="editors.xml#MB">Mattie Burkert</name>
				</respStmt>
				<respStmt>
					<resp>Composition and research of contextual annotations</resp>
					<name>Kaleb Beavers</name>
					<name>Matthew Bicakci</name>
					<name>Jessie Heine</name>
					<name>Kimberly Olivar</name>
				</respStmt>
				<respStmt>
					<resp>Definition of archaic and unfamiliar words</resp>
					<name>Annalise San Juan</name>
					<name>Ashia Ajani</name>
					<name>Rachel Peri</name>
				</respStmt>
				<respStmt>
					<resp>Page image integration</resp>
					<name ref="editors.xml#MB">Mattie Burkert</name>
				</respStmt>
```

**Comment by tonyahowe** [comment]
That looks great--much better! I wasn't thinking we could have multiple respStmts, this is great. Will probably need to update the schema.

**Comment by tonyahowe** [comment]
I've got a sample for you--it's here in https://anthologydev.lib.virginia.edu/work/Stuart/Stuart-Articles_of_Peace 

```
<respStmt>
                    <resp>Transcription, correction, and markup</resp>
                    <name ref="editors.xml#AJB">Austin Benson</name>
                </respStmt>
                <respStmt>
                    <resp>Correction</resp>
                    <name ref="editors.xml#JOB">John O'Brien</name>
                    <name ref="editors.xml#TH">Tonya Howe</name>
                </respStmt>
```

**Comment by wsalesky** [comment]
Yes,
