### ISSUE TITLE
alt text in images

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#186]
We need to have a way to render alt text on images, either in notes (these would be added by hand in the xml) or page images (automatically generated from existing xml).

For instance, in data/Shakespeare/shakespeare-tempest.xml, we have this note:

```
<note xml:id="Dee" target="Dee_" type="editorial"
                        resp="editors.xml#MUStudStaff"><graphic
                           url="notes/british-museum-john-dees-37447001.jpeg" alt="Photograph showing items belonging used in alchemy and early modern magic."/>It is often thought
                        that Prospero was modeled by Shakespeare on <persName type="lcnaf"
                           key="n79006490"><name>John Dee</name></persName>, a well-known polymath,
                        magus, and advisor to Queen Elizabeth I. According to the <ref
                           target="https://www.bl.uk/shakespeare/articles/prospero-a-renaissance-magus"
                           >British Library</ref>, a magus someone who "understands the cosmos and
                        man's place in it [sic]" through knowledge and experimentation in fields
                        such as chemistry (then alchemy) [...] </note>
```
We would want the image in the digital edition to include the alt text for accessibility.

In the same file, we have ```<pb n="2" facs="pageImages/002.png"/>```. We would like the page image to include alt text generated from existing data in the file, specifically **body/pb@n**, such that the alt text renders as: "Page **2**. More information about the page images used in this digital edition can be found in 'Sources'."

**Comment by wsalesky** [comment]
@tonyahowe What about graphic elements with no alt attribute? Do we want to generate one, or will this just be resolved as the data cleanup continues?

**Comment by wsalesky** [comment]
@tonyahowe  update on dev, if it looks good, we will move it to production.

**Comment by tonyahowe** [comment]
I can't see the sample in shakespeare-tempest.xml, because it's not showing up in the database (it is in there, and it's valid). I also can't seem to see the alt text on page images when I hover? I'm in Brave browser (chrome-based).

**Comment by tonyahowe** [comment]
Fixed it--sorry! https://anthologydev.lib.virginia.edu/work/Shakespeare/shakespeare-tempest

**Comment by tonyahowe** [comment]
@wsalesky  I don't see the alt text appearing on my browser (Safari).

**Comment by wsalesky** [comment]
@tonyahowe how about now?

**Comment by tonyahowe** [comment]
Sorry, I still don't see it. I'm in Chrome, now--the caption is there, though, fantastic!!

**Comment by tonyahowe** [comment]
I looked at the source of the webpage and the alt text is there, @wsalesky... I don't know why hover doesn't show it. Weird.

**Comment by wsalesky** [comment]
@tonyahowe I will have to add the hover display. The alt text does not automatically trigger mouseover text. Sorry, I should have thought of that.

**Comment by wsalesky** [comment]
Fixed.
