### ISSUE TITLE
caption under NOTE images

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#187]
We'd like to enable a caption beneath images included in notes. I know that canonical XML uses` <figure><graphic><head><figDesc>`, but it would work better for us if this information could be included by authors in the <graphic> tag, which is currently the only one used in the notes. Could we add an attribute "caption" or "source" to the graphic element, which could be rendered in small, italicized type beneath the image that shows in the popup? This would be where our contributors would be required to note source information. 

Is it possible to include a link out within the caption? If this is messy, let me know!

For instance, in shakespeare-tempest.xml, we might have 
```
<note xml:id="Dee" target="Dee_" type="editorial"
                        resp="editors.xml#MUStudStaff"><graphic
                           url="notes/british-museum-john-dees-37447001.jpeg" alt="Photograph showing items belonging used in alchemy and early modern magic." source="<ref target="https://www.bl.uk">The British Library</ref>"/>It is often thought
                        that [...]</note>
```

The caption would be rendered beneath the image in the popup, left-aligned, in small, italicized text as follows: _Source: [The British Library](https://www.bl.uk)_

I added this to the xml of shakespeare-tempest.xml, but I don't know if it will upload via github, as it's not validating!

**Comment by wsalesky** [comment]
Can you post a link to where in the xml this is, it will make testing easier. Thanks!

**Comment by tonyahowe** [comment]
This is to the shakespeare-tempest.xml file, but it's not appearing in the app; https://anthologydev.lib.virginia.edu/work/Shakespeare/shakespeare-tempest

**Comment by tonyahowe** [comment]
Oh-- I think I know why we can't see the test page; adding the alt text and the caption xml invalidates the document @wsalesky

**Comment by wsalesky** [comment]
@tonyahowe Yes, there is an error in the XML: 
https://github.com/LiteratureInContext/LiC-data/blob/development/data/Shakespeare/shakespeare-tempest.xml#L559

This is not well formed XML: 
`source="<ref target="https://www.bl.uk">The British Library</ref>"`

**Comment by tonyahowe** [comment]
Ah, I see, @wsalesky. Could we use the native "desc" attribute instead of source to form the content of the caption, and source (src?) to create the url link? Is it possible to turn the @desc text into the @source link? Or perhaps to simplfy just put (Source) into the caption with "Source" being a link to the URL? Here's the updated XML for the graphic element: 
<graphic url="notes/british-museum-john-dees-37447001.jpeg" alt="Photograph showing alchemical items belonging to John Dee, used in early modern magic, from the British Library." desc="Dee's spirit mirror and other alchemical objects" source="https://www.bl.uk/collection-items/john-dees-spirit-mirror"/>

This is in https://anthologydev.lib.virginia.edu/work/Shakespeare/shakespeare-tempest

**Comment by wsalesky** [comment]
@tonyahowe Yes, that should work.  I will work up a test on the dev server

**Comment by wsalesky** [comment]
Done. Check here: https://anthologydev.lib.virginia.edu/work/Shakespeare/shakespeare-tempest

**Comment by tonyahowe** [comment]
Excellent, thanks!!!
