### ISSUE TITLE
extra spaces after notes

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#189]
There are strange extra spaces after notes, and I can't find the source. For instance, 

in shakespeare-tempest.xml, the xml at line 527 renders with a space after the : 
```
<stage>A confused noise within: 'Mercy on us!'-- '<ref target="split_"
                     corresp="split">We split</ref>
                  <note xml:id="split" target="split_" resp="editors.xml#LD">The ship is splitting
                     in half.</note>, we split!'--'Farewell, my wife and children!'-- 'Farewell,
                  brother!'--'We split, we split, we split!'</stage>
```
renders with a space after the link and before the comma. This might be gotten rid of by moving the open **note** element right behind the close **ref** element, but they always get reformatted by Oxygen formatting.

In winkfield-female-american.xml, around line 428, there's a space after the link in the same fashion:

```originally, <ref target="Wingandacoa_" corresp="Wingandacoa"
						>Wingandacoa</ref>
					<note xml:id="Wingandacoa" target="Wingandacoa_" type="editorial"
						resp="editors.xml#UOStudStaff">
						<graphic url="notes/wingandacoa.jpeg"/>According to the <ref
							target="https://digital.lib.ecu.edu/roanokecolonies/view/Wingandacoa"
							>Joyner Library at East Carolina University</ref>, "Wingandacoa" is
						another name for the mainland of Virginia.</note>, part of the continent
```

**Comment by wsalesky** [comment]
These spaces are in the data, you should not allow automatic pretty print of TEI records as it can introduce spaces like this. There is no way for the xslt/xquery to know what spaces are important and which are not, so I generally preserve the spaces as found in the TEI.
