### ISSUE TITLE
author list

### ISSUE THREAD

**Issue by jobrien62** [LiteratureInContext/LiC-app#19]
The list of authors is currently alphabetical by first name--can we make this alphabetical by last name easily? I suspect most people will look for authors in the first instance that way.

**Comment by jobrien62** [comment]
accidentally assigned myself to this, but need a larger conversation....

**Comment by tonyahowe** [comment]
I agree—the names in the TEI had been all in one <persName> but now it’s separated into <surname> and <forename>. Now it’s possible to do Behn, Aphra (dates) in the browse by author page. Later we can consider adding a sort by last name or date, too!

**Comment by wsalesky** [comment]
Sure, should the display also be last name, first name (dates)?

**Comment by jobrien62** [comment]
Yes, if possible.

**Comment by wsalesky** [comment]
@jobrien62 @tonyahowe TEI clarification question. Which tei:author should I use for display? The one in the tei:titleStmt or the one in the tei:sourceDesc

Thanks.

**Comment by tonyahowe** [comment]
I think the tei:author, unless there's a reason not to. We duplicated it because the sourceDesc is a description of the whole object, analytic and monograph.

**Comment by wsalesky** [comment]
Okay. This should be set. Reopen if I missed anything.
