### ISSUE TITLE
Reader interfaces 2: chunking text

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#195]
Is there a way to easily allow readers on the fly to "chunk" the text? We have a lazy load already, but due to the nature of the project, some texts we want to have all on one page. But, this can be challenging for people to read. Can we have a "page by page" reading option somehow, or some other arbitrary word/character count advancement? Not sure what this would look like, so ideas are welcome!

**Comment by jobrien62** [comment]
Here's one example of this *kind* of thing, from the Thomas Gray Archive. https://www.thomasgray.org/texts/diglib/primary/1751/1/elcc. A box with back and forth buttons, etc. It looks to be using a carousel from a resource called "sharaholic." I'm sure that there are other examples out there as well.

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 Yes this is possible. We can offer options, page/chapter, etc. Let me know what you would like, or if it depends on the document structure, that is also fine. We can discuss options.
