### ISSUE TITLE
Publication Dates

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#20]
Is it possible to zero in on the publication dates a bit more granularly? All of our texts (for the time being) should have been published between 1660 and 1830 (ish). Perhaps using ten-year chunks instead of twenty-five-year chunks? This is also a TEI problem in that the publication information in the xml files isn't always there/consistent. 

I'll tag @brinascode and @sb8wb to help out with this and open an issue in LiC-data.

**Comment by wsalesky** [comment]
@tonyahowe Yes, we can make the intervals and the time span what ever you like. I also have a date slider function you could use if you prefer. 

Example: https://architecturasinica.org/research-tool.html

**Comment by wsalesky** [comment]
I updated this.

**Comment by tonyahowe** [comment]
Thanks! We are working, slowly, on making sure the sourceDesc has the correct analytic and bibliographic elements to make use of this.

**Comment by wsalesky** [comment]
Okay. You can close this if you would like.
