### ISSUE TITLE
Search results create links to the highlighted search result, but link goes to the page top

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#201]
When a user does a keyword search in the search box at the top, say for the word "death," the search results show the search phrase in context, highlighted. But it also adds a link to the text. A user would expect the link to go to that location in context, but the link just goes to the top of the edition in question. It would be great if the keyword link could go to the location in context. That may also entail reshaping the KWIC results from the search screen, so the KWICs are separated out?

**Comment by wsalesky** [comment]
@tonyahowe There is no reliable way to link to the results to the correct place on the page. I'm removing the links on the highlighted results.
https://github.com/LiteratureInContext/LiC-app/pull/318
