### ISSUE TITLE
Duplicate files in search

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#206]
When a text is searched using the search boxes (either of them), the resulting files are duplicated in the return list. This is not the case if the user just goes to browse. 
<img width="1800" alt="Screenshot 2023-10-18 at 10 12 01 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/478d21de-784c-4793-8281-fa1ff7034289">

**Comment by wsalesky** [comment]
Fixed

**Comment by tonyahowe** [comment]
Something wonky still seems to be happening: when I select, say, Claude McKay from the browse list, I see that he has 1 (accurately) text in the database. Clicking on it turns the noted 1 into 2. But the item itself is not showing up twice--here's a SS:
<img width="1550" alt="Screen Shot 2023-10-23 at 8 12 51 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/9964e64c-5b14-45c6-a973-427d0771678c">

**Comment by wsalesky** [comment]
@tonyahowe Hum, very interesting. I will do some more debugging. Sorry about that!

**Comment by tonyahowe** [comment]
No worries! There are also some texts not showing up anymore--this may be another issue, but Shakespeare's Tempest, for instance, was in the DB but is now not showing via the web app. It's in the data repository, and it validates, but it's not showing up. 

Here's another weird issue--when I go to browse authors/titles, and select authors, I cannot expand the + list of works--see the screen recording here. I'm using Safari right now. 


https://github.com/LiteratureInContext/LiC-app/assets/1153464/0361060e-380d-4312-bc67-80b17ae84ea8

**Comment by wsalesky** [comment]
No showing up on the development server, or production server? Or both?

**Comment by tonyahowe** [comment]
My screenshots and recordings are from the dev server; just checked the production server, and things are being counted correctly there, though the data is old (some things newly added are missing).

Definitely something weird happening with the counting--when I select Aphra Behn, who should have several works, nothing shows up:

![Screenshot 2023-10-24 at 10 31 47 AM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/7941b670-6e9f-4553-9082-3e05eee90e1a)

**Comment by tonyahowe** [comment]
Oooh, this might help-- in the list of authors on the right, Behn shows up twice--once with 2 texts associated, and once with 4. There are 4 texts--a poem (behn-clarinda), a play (behn-rover), a novella (behn-oroonoko), and a headnote (behn-headnote). The poem (behn-clarinda.xml) is not showing up:

![Screenshot 2023-10-24 at 10 40 09 AM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/bb7b9f6d-038a-43a8-9de0-3de4ca54c83e)

**Comment by wsalesky** [comment]
@tonyahowe Thanks for all the screen shots, this is helping. One note, I only see 3 works with Behn, Aphra as the author, the headnote does not have her as the author, it has John as the author, so it would not show up in the list. We may want to add something to headnotes to make them show up in the author lists, but currently the result is just for the author element. Hope to have a fix coming up soon, I have found and fixed at least one of the issues!

**Comment by wsalesky** [comment]
@tonyahowe I think this has been fixed. It is a little slow, but I am working on that as well.
