### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#209]
It doesn't look like the webhooks are working yet? John said they were, but then stopped.

**Comment by jobrien62** [comment]
It’s the dev site that is not working, and at the moment the webhooks are not updating; just checked on a couple of texts. John

From: Winona Salesky ***@***.***>
Date: Thursday, October 19, 2023 at 10:01 AM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Webhooks (Issue #209)

@tonyahowe<https://github.com/tonyahowe> @jobrien62<https://github.com/jobrien62> Can you recheck webhooks? (Also, let me know if it is development or production that is not working)

**Comment by wsalesky** [comment]
@jobrien62 the webhooks claim to have updated: wycherley-country.xml

Is there another document that is not updating? Or are you not seeing the updates to wycherley-country.xml?

**Comment by jobrien62** [comment]
I’m not seeing those updates. I also updated Burke, Reflections, and that doesn’t seem to show updates.


From: Winona Salesky ***@***.***>
Date: Thursday, October 19, 2023 at 10:27 AM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Webhooks (Issue #209)

@jobrien62<https://github.com/jobrien62> the webhooks claim to have updated: wycherley-country.xml

Is there another document that is not updating? Or are you not seeing the updates to wycherley-country.xml?

**Comment by jobrien62** [comment]
OK, I made changes both to spectator 10 and to the country wife.

The first change showed up. But then I made a second minor change to the country wife, and it did not show up. The hooks for that one seem to hold once, but then not beyond that. A second change in spectator 10 did show up, however. So it’s a little mysterious. I’ll keep testing (have to go to a meeting soon).

From: Winona Salesky ***@***.***>
Date: Thursday, October 19, 2023 at 10:48 AM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Webhooks (Issue #209)

@jobrien62<https://github.com/jobrien62> Can you try to make a new change? Just to test the webhooks, on the development branch?

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 I think this can be closed. Reopen if you have issues with loading files.
