### ISSUE TITLE
Timeline updates

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#212]
Some texts in the database use later editions as their imprint; however, we want the timeline to show the date most typically associated with it. For instance, in chaucer-prologue.xml line 67:  <date when="1900" timeline="1476">1900</date>. The @timeline should be what shows up as the date, but only for texts that include the attribute with content. Otherwise, use the existing date. 

In addition, we'd like the timeline to show only author, title, and date (as above), with the same link to the text. 

Thank you! :)

**Comment by wsalesky** [comment]
fixed
