### ISSUE TITLE
list view of collaborator annotations

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#22]
It looks like the wonderful list of all the annotations written by each contributor (which had been visible when each text was expanded) seems to have disappeared.

**Comment by wsalesky** [comment]
Yes, I noticed this. It is actually just for editors that do not have an `xml:id `assigned in the editor.xml file. If you click on your name that should still expand.

**Comment by tonyahowe** [comment]
Thanks!
