### ISSUE TITLE
Still getting some doubled authors in the browse view

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#220]
Some authors--Austen, Paine, Poe--are showing up as two items in the browse view. For instance, Austen shows up twice, first with 1 associated text, and then with 3 associated texts. This must be a problem in the XML, but I can't figure it out! Thanks @vbscott!

https://github.com/LiteratureInContext/LiC-app/assets/1153464/97e4bd47-dc3d-42b3-b454-6d8bca6cf1b5

**Comment by wsalesky** [comment]
Should be fixed now.
