### ISSUE TITLE
Bug!  Error generated on Winkfield-Female-American.xml

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#221]
A colleague has a paper coming out soon about her work on this piece: [https://anthologydev.lib.virginia.edu/work/Winkfield/winkfield-female-american](https://anthologydev.lib.virginia.edu/work/Winkfield/winkfield-female-american) 

But it's throwing an error: 
![Screenshot 2023-11-08 at 4 03 53 PM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/f122a48c-9f85-4710-a182-d6ba2979ab63)

**Comment by wsalesky** [comment]
@tonyahowe Any chance you can update the respStmt to match the new format? That is what is causing the issue. I can code around it, but if we are updating them anyway, this would be the time.

**Comment by tonyahowe** [comment]
Fabulous—yes, I can do that tomorrow. Thanks!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tonyahowe** [comment]
I made the updates--the bug persists, but the edits are on GitHub: https://github.com/LiteratureInContext/LiC-data/blob/development/data/Winkfield/winkfield-female-american.xml

**Comment by tonyahowe** [comment]
The page shows now @wsalesky ! However, all the main title displays for texts in the db seem to have disappeared: 
<img width="1148" alt="Screen Shot 2023-11-09 at 4 33 08 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/87e1268c-62eb-4e3d-9fa2-ae82e09ff205">

**Comment by wsalesky** [comment]
@tonyahowe I believe this is now fixed.
