### ISSUE TITLE
expandable icons at top of text

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#226]
The expandable icons (for source texts and editorial statements) don't change when opened--the start at +, but when opened, the remain at +:

<img width="1071" alt="Screen Shot 2023-11-09 at 4 52 51 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/f22b0e65-8970-4de3-99f8-a18d6fa546dc">

**Comment by wsalesky** [comment]
Fixed.
