### ISSUE TITLE
Link to contributor form not visible anymore

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#237]
The link to the contributor form isn't visible anymore. Here's the link: [https://forms.gle/sxEMEZWcYY1JA1BJ9](https://forms.gle/sxEMEZWcYY1JA1BJ9 )

<img width="578" alt="Screenshot 2023-12-01 at 2 19 25 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/86376510-aaa7-4975-be39-a904f85b030c">

**Comment by tonyahowe** [comment]
It should be showing up at the top of the contributors page

**Comment by tonyahowe** [comment]
(in the empty space in the image)

**Comment by wsalesky** [comment]
Fixed: https://github.com/LiteratureInContext/LiC-app/pull/246
