### ISSUE TITLE
audio

### ISSUE THREAD

**Issue by jobrien62** [LiteratureInContext/LiC-app#238]
It would great to add sound files to texts. We can use Librivox (or other) public domain audio files. Ideally, some kind of box in the text that a reader could click on to get an audio file that they could listen to while scrolling through the text. I've jury rigged a link for The Deserted Village, but that takes the reader to another window. The TEI <media> element doesn't seem to be working right now, but that would be a logical element to use.

**Comment by wsalesky** [comment]
@jobrien62 can you link to the correct work? And maybe the line #? (just highlight it in gihub, and add the link to the issue.)
Thanks!

**Comment by jobrien62** [comment]
Here's a link: https://github.com/LiteratureInContext/LiC-data/blob/development/data/Goldsmith/goldsmith-deserted.xml#L221C6-L223C189. I've highlighted the lines in there (I think it's about line 221-223). Thanks!

**Comment by wsalesky** [comment]
Done! See: https://anthologydev.lib.virginia.edu/work/Goldsmith/goldsmith-deserted

**Comment by jobrien62** [comment]
Fantastic! Thank you!

From: Winona Salesky ***@***.***>
Date: Thursday, January 11, 2024 at 1:28 PM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] audio (Issue #238)

Done! See: https://anthologydev.lib.virginia.edu/work/Goldsmith/goldsmith-deserted

**Comment by tonyahowe** [comment]
So cool. Thanks!
