### ISSUE TITLE
Timeline again

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#239]
There is some duplicated data in the timeline view, and it would be good to have book/container titles in italics (as in the citations). Can we:

1. Remove the date from the end of the main title (circled in red), 
2. remove the period from the end of the title/before the date (indicated with arrow), and
3. Put any titles in the `monogr` element in italics (keep `analytic` in quotes (see underlined title)

<img width="909" alt="Screen Shot 2023-12-30 at 1 37 29 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/1a4eb24a-2b44-4f9e-b9b5-534daa5330fa">
<img width="1077" alt="Screen Shot 2023-12-30 at 1 37 11 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/1345eae1-5c7b-433b-9574-49d6b71d9fe1">

**Comment by wsalesky** [comment]
Fixed here: https://github.com/LiteratureInContext/LiC-app/pull/247
