### ISSUE TITLE
Merge into Master

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#24]
@tonyahowe @jobrien62 @cruotolo

I would like to merge the design branch into the main codebase tomorrow if you are good with the changes.

**Comment by tonyahowe** [comment]
I think we are good to go with this first merge!

**Comment by wsalesky** [comment]
Done. I will set up webhooks for the application and the data for the master branch. Then you can push your changes to production whenever you are ready.
