### ISSUE TITLE
Notes and Images in Notes Rendering (important)

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#240]
We are trying to get the new schema and data updated prior to our presentation at MLA, and I think I see what is wrong. The `p` attribute inside notes is causing rendering errors. When I remove the `p`, the note displays mostly as expected, but some parts are still rendered in line. We need to be able to show paragraphs so that notes with more than one paragraph render correctly, but it should also render without the `p`.

See for instance [wheatley-poems.xml](https://anthologydev.lib.virginia.edu/work/Wheatley/wheatley-poems), line 665 and following. The paragraph now seems to cause the body of the note to appear inline with the text. I think the addition of the graphic attributes is part of the problem?

**Screenshots with `p`:** 
<img width="997" alt="Screenshot 2023-12-31 at 11 37 35 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/5064474f-f4cd-4c92-b1b0-4eac7c4366cc">

<img width="1033" alt="Screenshot 2023-12-31 at 11 45 11 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/1d912a34-d4d6-42a1-8ece-7364209958d3">

**Here is an example of a note with image WITHOUT `p` in [haywood-fantomina.xml](https://anthologydev.lib.virginia.edu/work/Haywood/haywood-fantomina), line 630 and following:**

<img width="1000" alt="Screenshot 2023-12-31 at 11 48 17 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/81c08af1-9ef6-47c9-8b81-c84d83a8810c">
<img width="1278" alt="Screenshot 2023-12-31 at 11 47 44 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/4e7870ac-097b-4408-99a8-c84cf5764d8b">

**Comment by wsalesky** [comment]
@tonyahowe I think this has been resolved by the other fix to graphic/image display.

**Comment by tonyahowe** [comment]
Hmmm... The Poe example from the other issue was fixed, but that was also dealing with a different file structure. This one still seems to be happening--see for instance the wheatley-poems.xml text line 290ff (see below)--the Occom popup text is appearing in line AND in the popup, now, but the image is full size and also in-line: 
<img width="1305" alt="Screenshot 2024-01-03 at 4 01 42 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/cdfa7850-1a1c-489a-8998-428ea116776d">

In the haywood-fantomina.xml example, the "box" popup content (line 283) is inline, as is the image; the popup is empty:
<img width="1305" alt="Screenshot 2024-01-03 at 4 05 11 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/2f587674-75ec-416b-aebf-dde4985546ef">

The "barge" popup (line 630) from the same document is similar, but here the popup does have some text: 
<img width="1305" alt="Screenshot 2024-01-03 at 4 05 23 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/40a4cbc8-4ad8-4862-b6c8-b0c3322cd832">

**Comment by tonyahowe** [comment]
It looks like there's also a weird indentation problem, too--not sure where that's coming from?

**Comment by tonyahowe** [comment]
The author popup in haywood-fantomina.xml is showing up correctly, but none of the others are. Weird!

<img width="987" alt="Screenshot 2024-01-03 at 5 10 36 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/67fa0bb9-e7d9-4172-ad14-4e23477e4a30">
