### ISSUE TITLE
Broken links from author browse page

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#241]
When clicking into a text from the [author browse page](https://anthologydev.lib.virginia.edu/browse.html?view=author), we get an error 404:

<img width="1305" alt="Screenshot 2024-01-02 at 3 17 48 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/375a0c7f-dbf2-4470-af79-0dc10136dccc">

**Comment by wsalesky** [comment]
Fixed here. https://github.com/LiteratureInContext/LiC-app/pull/245
