### ISSUE TITLE
placement of desc/source captions for images

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#242]
Is it possible to place captions for images underneath the images? See this example, the headnote for Poe, where the image appears to the right but the desc/source caption appears in line with text:

<img width="987" alt="Screenshot 2024-01-03 at 9 24 58 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/084fe978-4eeb-4d41-90a0-2adc22341c93">

**Comment by wsalesky** [comment]
Fixed
