### ISSUE TITLE
Weird issue with contributor information

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#243]
I cannot figure out why this is happening--but Sarah Ficke is somehow associated with my record, Tonya Howe. See the persons/places graph, and the list of people:

<img width="941" alt="Screenshot 2024-01-03 at 9 31 08 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/09499a27-d84d-4f1d-8504-d96ab68b43d6">
<img width="783" alt="Screenshot 2024-01-03 at 9 33 13 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/570d14d3-6d79-4eee-b2b7-7dfbef592876">

In the latter case, the external link takes the user to Tonya Howe's ORCID page. I've looked at the XML for these texts, and the editors.xml page, but I can't find the problem! It's super weird.

**Comment by wsalesky** [comment]
@tonyahowe I just re ran the script that builds the linked data images. I think it looks correct now.
