### ISSUE TITLE
Map bug

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#251]
The links from the map application to the texts is buggy--the links are broken. See the capture below!

https://github.com/LiteratureInContext/LiC-app/assets/1153464/ba5e3140-3ab4-4d0a-badf-54501d4340df

**Comment by wsalesky** [comment]
@tonyahowe Thanks, I will take a look!

**Comment by wsalesky** [comment]
@tonyahowe Is this working now? If not, is it just the one record? Multiple records?

**Comment by tonyahowe** [comment]
Yes, working now! Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
