### ISSUE TITLE
Spacing of splash image and text on large display

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#26]
On a big screen (wide), the first splash image doesn't quite display correctly; when we resize the page, it does. Not sure if this is a big issue for now.... :)

![Screen Shot 2019-03-19 at 12 19 07 PM](https://user-images.githubusercontent.com/1153464/54623154-5cb1da00-4a41-11e9-85ce-8a4492c9a3e0.png)

**Comment by tonyahowe** [comment]
The text block is also missing some information; is there a way to ensure that all the text gets on there? I've condensed it a bit:

> _Literature in Context: An Open Anthology of Literature, 1660-1830_, is a web-accessible and mobile-friendly digital anthology of contextualized, machine-readable literature in English designed for use by students, teachers, and the general public. Anticipating these pieces being used in the classroom, we strive to make texts that are authoritative, citable, and printable, as well. 
> 
> At once an Open Educational Resource and a digital humanities project that seeks to bring to life the literature of the long eighteenth century, _Literature in Context_ also will also provide resources to help instructors at the college level engage students in the task of editing and annotating literary texts to be added to the collection. By including students in the production of the anthology, the project foregrounds how the public construction of knowledge is essential to understanding the modern world.
> 
> Sponsored by funding from the National Endowment for the Humanities and led by teams of scholars, students, and librarians at Marymount University and the University of Virginia, our goal is a platform for establishing authoritative, contextualized works that teachers and students can use with confidence. In this way, we hope to provide a tool for the thoughtful, collaborative editing and dissemination of our shared humanistic heritage. 

If we can't get the text and the image on one rotating page, perhaps we can put the text on the first page, and the image by itself on the second?

**Comment by wsalesky** [comment]
@tonyahowe That image is a little tricky on the splash page. The slides are a fixed height (400px) with no scrolling, a part of a javascript library. We could change the height of the slides if you like?

**Comment by wsalesky** [comment]
@tonyahowe I think this can be closed?

**Comment by tonyahowe** [comment]
Yes, thanks!
