### ISSUE TITLE
Sorting from browse

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#261]
From browse, the sorts don't seem to be working; each option changes the URL, but the order remains the same:

https://github.com/LiteratureInContext/LiC-app/assets/1153464/c13ba47b-4bec-40ac-9ed8-1404a074de62

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 @cruotolo Looks like the indexes have been corrupted. I will check on the best way to do a back up and restore and then coordinate with Dave. Browse sort works on my local machine, so once the indexes are fixed we should be fine.

**Comment by wsalesky** [comment]
Finally fixed.

**Comment by tonyahowe** [comment]
This is awesome, thanks!
