### ISSUE TITLE
Sorting from coursepack

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#262]
The coursepack sort partially works (?) though I'm not sure how sort by date is understood. See this screencast when selecting sort by date:

https://github.com/LiteratureInContext/LiC-app/assets/1153464/d063c24e-e019-4335-8a32-154c53f1ed53

**Comment by wsalesky** [comment]
fixed.

**Comment by tonyahowe** [comment]
The sort doesn't seem to work all the way--Title is the only sort that does as expected? See video:

Screen Recording 2024-07-04 at 7.13.03 PM

**Comment by wsalesky** [comment]
Fixed
