### ISSUE TITLE
TH texts showing up as SF texts

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#263]
Not sure what's happening here--texts that are associated with me (editors.xml#TH or ORCID) are being connected to another contributor. 
![Screenshot 2024-02-07 at 9 36 30 AM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/bbfcc224-a4da-4708-a97f-0d9658eb7774)
![Screenshot 2024-02-07 at 9 37 46 AM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/1d9e82bd-90e7-492c-b748-3a0a9810dac3)
![Screenshot 2024-02-07 at 9 37 21 AM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/9f432378-71ff-4dcd-8705-6cba5d267b62)
![Screenshot 2024-02-07 at 9 36 43 AM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/54e6aab6-18f7-4383-852f-44effb2274ec)

**Comment by wsalesky** [comment]
Updated lod data files. Not sure what happened to them, but the update to the data seems to have corrected the issue.
