### ISSUE TITLE
Should we have editors show up in linked data? 

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#264]
Currently, both @jobrien62, @tonyahowe, and other editors noted in the header--and/or as contributors? not sure where the data vizzes are pulling from--are showing up in the linked data vizzes. Do we want this? See issue #263 images.

**Comment by wsalesky** [comment]
@tonyahowe I think it is pulling from editors, we can easily  suppress them if you like.

**Comment by tonyahowe** [comment]
Yes, let's suppress that. Thanks!!

**Comment by wsalesky** [comment]
Done
