### ISSUE TITLE
unexpected file 

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#274]
[This text by Bradstreet](https://anthologydev.lib.virginia.edu/work/Bradstreet/bradstreet-davids ) doesn't seem to have an xml file in the github data site (dev site). There is a duplicate file called bradstreet-davids-lamentation.xml, and that is the one that should be kept. Not sure why bradstreet-davids (the second in the list below) is showing up?
<img width="822" alt="Screenshot 2024-02-17 at 12 13 09 PM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/f0c3dbc3-bb52-4c47-b092-fa99a24e6736">

**Comment by wsalesky** [comment]
I removed it from the server.
