### ISSUE TITLE
Login functionality

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#279]
We cannot login using existing or by creating new login identities; the failure is silent.

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 Please test now, this was a permissions error. Close if it is resolved. Thanks

**Comment by wsalesky** [comment]
@tonyahowe has this been resolved?

**Comment by tonyahowe** [comment]
Sorry, I haven’t gotten to it yet—I’ll look this afternoon!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tonyahowe** [comment]
Login and create user seems to work! I am having trouble creating coursepacks with login, though that's a different issue. :)
