### ISSUE TITLE
Error when attempting to download a XML, PDF, or EPUB

### ISSUE THREAD

**Issue by jeremyboggs** [LiteratureInContext/LiC-app#281]
Very sorry if I should share this some other way! And very sorry if this issue is replicated in an existing ticket.

I encounter the following error when I attempt to download a TEI/XML, PDF, or EPUB for any document:

```
/db/apps/LiC/modules/content-negotiation/content-negotiation.xqlerr:XQST0059 error found while loading 
module cntneg: Error while loading module content-negotiation.xqm: error found while loading module tei2fo: 
Error while loading module tei2fo.xqm: namespace URI declared by module (http://LiC.org/tei2fo) does not 
match namespace URI in import statement, which was: http://LiC.org/apps/tei2fo
```

To replicate:
- Visit https://anthology.lib.virginia.edu/work/Swift/Swift-Gulliver
- Click the "Download" button just below the document title/author information.
- Choose one of the download options.

**Comment by wsalesky** [comment]
@jeremyboggs Thanks for the bug report. I will look into it.

**Comment by wsalesky** [comment]
Resolved with latest code deployment
