### ISSUE TITLE
Browse items--exclude templates and headnotes? 

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#288]
The sort by date option in the browse feature is great! It reveals that the headnotes and templates are included in the texts. Would it be possible to exclude those from the browse feature? Or not exclude them entirely, but not have them show up? They could be searchable, but I don't know how helpful it is to show them in the entire browse list.

**Comment by wsalesky** [comment]
Which would you rather? Not returned in search at all? Or returned in search, but not browse?

**Comment by tonyahowe** [comment]
I think returned in search, not in browse.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wsalesky** [comment]
Fixed
