### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#292]
Can we please add the VIVA logo and the GMU logo to the front splash page? And swap out twitter logo for x...
![VIVALogo5_smal](https://github.com/LiteratureInContext/LiC-app/assets/1153464/b149c787-c5d1-4f28-a1fc-439b5841e85b)
![twitter-x](https://github.com/LiteratureInContext/LiC-app/assets/1153464/0916bbaa-9528-4d96-9966-c9612a98bd42)
![university-HorizontalRGB](https://github.com/LiteratureInContext/LiC-app/assets/1153464/f9e6bfe9-297f-4cea-bc14-f11b603fbaf3)

**Comment by wsalesky** [comment]
@tonyahowe Can you email me the images?

**Comment by tonyahowe** [comment]
Done!

**Comment by wsalesky** [comment]
@tonyahowe Sorry, also need links to where these should go  mostly for VIVA, George Masson is self explanatory.

**Comment by wsalesky** [comment]
Done
