### ISSUE TITLE
Login and coursepack issues

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#295]
It looks like the login and coursepack aren't working... not sure why I was able to create an id earlier, but when we were working through it last week, it didn't. 
- login: silently fails
-  create coursepack fails
- add to a new coursepack silently fails (these are probably related)

Can you add some feedback to the results/popups so a user knows what happened? We added "success!", I remember, but nothing (I think?) when failure occurs.

**Comment by wsalesky** [comment]
@tonyahowe Can you try again? Also, what browser are you using? I was able to create a new user, login and create a new coursepack.

**Comment by tonyahowe** [comment]
Hmmm. It's working for me now, too, in Chrome. Not sure what's going on here. @jobrien62, what browser were you using when this didn't work for you?

**Comment by tonyahowe** [comment]
Couple updates:

This all works for me, but there are some silences and other bugs. When I add texts from checkbox to a coursepack, I get duplications in the popup. They aren't duplicated in the actual coursepack, though: 

![Screenshot 2024-05-15 at 12 42 33 PM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/366bc03a-3ae7-4232-85a7-bc9cc3eacbce)

Also, when adding a selection to a coursepack from the left-hand widget, there's no indication of success/failure; when I clicked save again, the selection was saved again, but no indication of success. See this screencast: https://app.screencast.com/9jk6sKLb71unR

**Comment by jobrien62** [comment]
I still cannot log in or create a new account; I’m using both Chrome and Safari on a Mac. Don’t know why!

From: Tonya Howe ***@***.***>
Date: Wednesday, May 15, 2024 at 12:54 PM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Login and coursepack issues (Issue #295)

Couple updates:

This all works for me, but there are some silences and other bugs. When I add texts from checkbox to a coursepack, I get duplications in the popup. They aren't duplicated in the actual coursepack, though:

Screenshot.2024-05-15.at.12.42.33.PM.png (view on web)<https://github.com/LiteratureInContext/LiC-app/assets/1153464/366bc03a-3ae7-4232-85a7-bc9cc3eacbce>

Also, when adding a selection to a coursepack from the left-hand widget, there's no indication of success/failure; when I clicked save again, the selection was saved again, but no indication of success. See this screencast: https://app.screencast.com/9jk6sKLb71unR

**Comment by cruotolo** [comment]
Same for me – I can’t create a new account or log into the old ones, on either dev or production, using Chrome or Safari.

-Chris

From: jobrien62 ***@***.***>
Date: Wednesday, May 15, 2024 at 9:19 PM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Login and coursepack issues (Issue #295)
I still cannot log in or create a new account; I’m using both Chrome and Safari on a Mac. Don’t know why!

From: Tonya Howe ***@***.***>
Date: Wednesday, May 15, 2024 at 12:54 PM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Login and coursepack issues (Issue #295)

Couple updates:

This all works for me, but there are some silences and other bugs. When I add texts from checkbox to a coursepack, I get duplications in the popup. They aren't duplicated in the actual coursepack, though:

Screenshot.2024-05-15.at.12.42.33.PM.png (view on web)<https://github.com/LiteratureInContext/LiC-app/assets/1153464/366bc03a-3ae7-4232-85a7-bc9cc3eacbce>

Also, when adding a selection to a coursepack from the left-hand widget, there's no indication of success/failure; when I clicked save again, the selection was saved again, but no indication of success. See this screencast: https://app.screencast.com/9jk6sKLb71unR

**Comment by jobrien62** [comment]
OK, Ill try that. See you tomorrow.

From: Winona Salesky ***@***.***>
Date: Thursday, May 16, 2024 at 9:46 AM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Login and coursepack issues (Issue #295)

@tonyahowe<https://github.com/tonyahowe> @jobrien62<https://github.com/jobrien62> @cruotolo<https://github.com/cruotolo> Maybe we can take a look at our meeting tomorrow. Also, please try a hard refresh of your browsers before testing the login.

**Comment by tonyahowe** [comment]
I tried this morning on my Mac, and I think that’s the problem—login works on PC, but not on Mac?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jobrien62** [comment]
Yes, I think that’s it; I’ve not been able to login or create a new account on any browser on my Mac. See you next week.

From: Tonya Howe ***@***.***>
Date: Friday, May 17, 2024 at 2:43 PM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Login and coursepack issues (Issue #295)
I tried this morning on my Mac, and I think that’s the problem—login works on PC, but not on Mac?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tonyahowe** [comment]
Okay, I'm able to log in to my account on both Safari and Chrome from a Mac. But, a few problems:

1. There is no indication of success or failure at login, except the username in the top right. Can we add a couple?
2. When I add a text to a new coursepack, I get a success popup! Cool. But, when I add a text to an existing coursepack, I don't get a popup of any sort--indicators would be helpful here too.
3. Also, something weird happens on **Chrome**. When I go to the Coursepack nav item, my new coursepack doesn't show up. But, when I go to my Account, it does show up. See video below. It DOES appear as it should in Safari. 
4. But, in **Safari**, there's no indication of success or failure when I add a text to an existing coursepack. See video below. The new addition does appear in the coursepack, and the coursepack is visible in the coursepack nav item. 


https://github.com/LiteratureInContext/LiC-app/assets/1153464/27c66f3d-a200-40ac-86ea-6ce1a24c8a5d

https://github.com/LiteratureInContext/LiC-app/assets/1153464/9133470a-f95b-4165-89c4-d5a9e1fb9c34

**Comment by wsalesky** [comment]
Fixed here: 
https://github.com/LiteratureInContext/LiC-app/pull/324
https://github.com/LiteratureInContext/LiC-app/pull/323

Still need to add more info to login success or failure, opening a new issue for that, as it is unrelated to coursepack issues.
