### ISSUE TITLE
Linked data view from page

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#297]
Two things: 

1. In many many cases, there are no placeNames associated with a text (or maybe one, in the header). This means that when a user checks the linked data, it opens an empty (or mostly empty) map. Is it possible to do a count test? if there are 2 or more placeNames with keys, show the map? 
2. It would be nice to be able to tab through (defaulting to the map) other linked data views, with the same caveat as above, in any given text.

**Comment by tonyahowe** [comment]
Or possibly a drop-down? Not sure of the UX

**Comment by wsalesky** [comment]
First pass: https://github.com/LiteratureInContext/LiC-app/pull/317


@tonyahowe @jobrien62  @cruotolo
