### ISSUE TITLE
Signposting for Hypothesis

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#298]
We'd like to have a bit more signposting for hypothesis in the popup--perhaps a title? "Social annotation with Hypothesis"?

**Comment by wsalesky** [comment]
@tonyahowe Can you clarify where you want this? There is a limited amount we can change with Hypothesis.

**Comment by tonyahowe** [comment]
Perhaps just above the icons in the popup?

![Screenshot 2024-05-15 at 12 54 42 PM](https://github.com/LiteratureInContext/LiC-app/assets/1153464/11c75370-a5f4-4189-9d7f-c4955beb824c)

**Comment by wsalesky** [comment]
@tonyahowe This is not configurable on our side.
