### ISSUE TITLE
Design home page, colors and fonts. 

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#3]
A discussion area for the look and feel of the website. Current design: 
<img width="1421" alt="Screen Shot 2019-03-15 at 9 41 34 AM" src="https://user-images.githubusercontent.com/1168206/54435310-92378a00-4706-11e9-965f-0db29f07082c.png">

This is felt to be to close to the Early Novels Database (https://earlynovels.github.io/), very similar endpaper color.

Options:
1. 
<img width="1432" alt="Screen Shot 2019-03-15 at 9 43 16 AM" src="https://user-images.githubusercontent.com/1168206/54435405-cb6ffa00-4706-11e9-891b-1c763f70cd59.png">

2. 
<img width="1418" alt="Screen Shot 2019-03-15 at 9 39 35 AM" src="https://user-images.githubusercontent.com/1168206/54435418-d165db00-4706-11e9-8fc4-30a65e096ae7.png">

3.
<img width="1404" alt="Screen Shot 2019-03-15 at 9 39 23 AM" src="https://user-images.githubusercontent.com/1168206/54435419-d165db00-4706-11e9-944c-1b0413bac95b.png">

@tonyahowe @jobrien62 - please review and discuss.

**Comment by tonyahowe** [comment]
@jobrien62, I am torn between options 1 and 2--1 is more colorful and uses fabric from the period, gesturing toward materiality and context. 2 I like for the endpaper/printing connection. Either would be great--which do you prefer?

**Comment by jobrien62** [comment]
I like the color of 1, and the way it plays on “text”/“texture.” 2 has the more obvious link, though, to the materiality of books themselves. But (and here I have the counsel of my wife, who is seeing this for the very first time) the red color in the fabric is so beautiful and eye-catching that I’m inclined to lean towards it. It’s more inviting. John

**Comment by tonyahowe** [comment]
Let’s do it! #1 it is!

**Comment by wsalesky** [comment]
Tagging @cruotolo

**Comment by wsalesky** [comment]
Done.
