### ISSUE TITLE
Sort by

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#30]
The sort by date feature doesn't seem to work, though this is also probably a problem in the data. Can we add a sort by date ascending/descending? 

Regarding the sort by title; is there a way to eliminate from consideration leading words like "A," "An," "The"? What do you think, @jobrien62 -- is this worthwhile?

**Comment by wsalesky** [comment]
Yes, this is pretty easy, just come up with a comprehensive list of leading words.

**Comment by tonyahowe** [comment]
I think just A, AN, THE would be the words most typically used that should be excluded. Thank you, Winona!

**Comment by wsalesky** [comment]
How does this look: https://anthologydev.lib.virginia.edu/browse.html

Would you like to filter numbers out as well?

**Comment by wsalesky** [comment]
@tonyahowe Can this be closed?

**Comment by tonyahowe** [comment]
I think this works! John and I are talking today about the project--we will put up any other issues here!
