### ISSUE TITLE
Generated TOC for long texts?

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#302]
The long texts are challenging to read, despite the lazy load. Is it possible to provide an option to view whole text, or page by page? Other alternatives? Perhaps there could be an item at the top of each text page, as with sources/citation/linked data/download/etc, so folks can elect to read chunk by chunk, but default to the lazy load?

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 @cruotolo Can you list some works that have sections? I did some spot checking, mostly I see page breaks only. I can do an interface that allows you to 'page' through the content, but that will get old for the longer records. Do you have any with chapters? Or other types of sections. If so leave a list of sample records on this issue for me to test the variouse options.

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 @cruotolo This is on the dev site. There will need to be some refining of the code and also of the data as the data is irregular. We can discuss.

**Comment by tonyahowe** [comment]
Cool, thanks. The toc seems to have disabled page images and annotation pop-ups?

**Comment by wsalesky** [comment]
Opps! I will get that fixed. Sorry.

**Comment by wsalesky** [comment]
@tonyahowe can you send me an example with a annotation popup so I can test it locally?

**Comment by tonyahowe** [comment]
It looks like the annotations are now working! But the page images still aren’t. I was looking at “The Waste Land” https://anthologydev.lib.virginia.edu/work/Eliot/eliot-waste-land?view=pageImages

From: Winona Salesky ***@***.***>
Date: Tuesday, July 30, 2024 at 11:28 AM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: Tonya Howe ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Generated TOC for long texts? (Issue #302)

@tonyahowe<https://github.com/tonyahowe> can you send me an example with a annotation popup so I can test it locally?

**Comment by wsalesky** [comment]
Fixed

**Comment by tonyahowe** [comment]
❤️

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jobrien62** [comment]
Excellent!

From: Tonya Howe ***@***.***>
Date: Tuesday, July 30, 2024 at 4:37 PM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] Generated TOC for long texts? (Issue #302)
❤️

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wsalesky** [comment]
@wsalesky add function to coursepack? Not sure how this will work.
