### ISSUE TITLE
Linked data: Persons in collection

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#303]
The linked data page for people referenced in the collection is very long and undifferentiated. Could we:
1. Paginate it,
2. Provide a way to scroll by alphabet as in this browse example, or a simple horizontal option (maybe A-C, D-F, and so on, depending on numbers?):
<img width="279" alt="Screenshot 2024-05-03 at 9 08 21 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/f42a88af-36e0-48f4-9da5-866eccfc4982">
3. and only include persNames with keys? This would exclude character names.

**Comment by wsalesky** [comment]
Added: https://github.com/LiteratureInContext/LiC-app/pull/308
