### ISSUE TITLE
Network Graph: People/Places/Texts

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#305]
The network of people/places/texts has a weird invisible border created by the nodes. Is it possible to expand this somehow, or make it responsive to the size of the page, and/or expand the height of the available space so it eliminates the blank space right/left? 

<img width="1512" alt="Screenshot 2024-05-03 at 9 13 12 AM" src="https://github.com/LiteratureInContext/LiC-app/assets/1153464/88d72f57-7671-4335-8023-82981601157a">

**Comment by wsalesky** [comment]
Fixed
