### ISSUE TITLE
webhooks?

### ISSUE THREAD

**Issue by jobrien62** [LiteratureInContext/LiC-app#316]
The dev site seems not to be updating when revised or new texts are uploaded. In the past, this has been a webhooks issue--is that it again? In any case, I've been uploading some changes and have a couple of new texts to upload, which are not showing up to check.

**Comment by wsalesky** [comment]
I will check this morning On Jun 26, 2024, at 2:59 AM, jobrien62 ***@***.***> wrote:﻿
The dev site seems not to be updating when revised or new texts are uploaded. In the past, this has been a webhooks issue--is that it again? In any case, I've been uploading some changes and have a couple of new texts to upload, which are not showing up to check.

**Comment by wsalesky** [comment]
@jobrien62 Should be good. Somehow the git-sync code reset. I will investigate, but it is working now.

**Comment by jobrien62** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
