### ISSUE TITLE
Contributor errors

### ISSUE THREAD

**Issue by brinascode** [LiteratureInContext/LiC-app#33]
Hi Winona,
Would be great if you could address the following issues:
--The "see all annotations" link (found in the Contributors page, after you click on a given contributor who has more than 1 contribution) returns an error.
--Contributor notes in the actual texts have links that link to the Contributor page that belonging to the author of the note. These links also return errors. 
Thanks!

**Comment by wsalesky** [comment]
Fixed!

**Comment by tonyahowe** [comment]
Thank you!
