### ISSUE TITLE
Reset password / Create new user

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#333]
There doesn't seem to be a way to reset one's password--there's email gathered on creating an account. I'm still having trouble with the login functionality, and I tried to create a new user--to no avail. It just hangs on the "Create Account" button and doesn't go further. I'm on a Macbook using Chrome. Also, note the weird extended lines on the reset password popup. 

![Screenshot 2024-07-30 at 1 21 41 PM](https://github.com/user-attachments/assets/e04d8a4b-c116-48b6-9116-e905cd0c7dd3)

![Screenshot 2024-07-30 at 1 24 39 PM](https://github.com/user-attachments/assets/e252fead-ae6b-41bb-b294-321c2baa5248)

**Comment by wsalesky** [comment]
@tonyahowe dev or prod?

**Comment by tonyahowe** [comment]
Both 😞

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wsalesky** [comment]
@tonyahowe I think we will need to go over this in our meeting, I can not reproduce this.
