### ISSUE TITLE
Ability to edit title and description of coursepacks

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#341]
It would be helpful to be able to edit the title and description of existing coursepacks.

**Comment by tonyahowe** [comment]
I don't see where this is available; I logged on, and looked at my coursepacks. Maybe I'm looking in the wrong area?
<img width="1379" alt="Screen Shot 2024-10-21 at 2 12 01 PM" src="https://github.com/user-attachments/assets/6b87cec0-3ddc-4e97-b836-264f1e543948">
<img width="1386" alt="Screen Shot 2024-10-21 at 2 12 21 PM" src="https://github.com/user-attachments/assets/36f02676-fb97-4307-99d2-4e9db4c876a4">

**Comment by wsalesky** [comment]
Interesting. It looks like a permissions error. It currently works if you are logged in as admin. I will troubleshoot the non admin accounts and see what is going on.

**Comment by wsalesky** [comment]
Updated. Please test. @tonyahowe

**Comment by wsalesky** [comment]
@tonyahowe how does this work now?

**Comment by tonyahowe** [comment]
Yes!! It works great! 😊

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
