### ISSUE TITLE
Prod site duplicating excerpts in coursepack

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#342]
A weird thing.... When I select excerpts (example is Robinson Crusoe in this cp: https://anthology.lib.virginia.edu/coursepack/EN161MarymountUniversitySpring20234) they are being mysteriously doubled. I also don't know how the tiny excerpt got on there... but it, too, is duplicated.

**Comment by tonyahowe** [comment]
I think this is a related problem; when I add an excerpt of the first 3 chapters of Equiano, another long text, the entirety of the text is added--but as a selection. Weirdly, it starts at the point I selected (so it doesn't include earlier content). THis is in the same coursepack as above.

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 @cruotolo Can this feature be retested. It should be fixed, but I need verification. Thanks!

**Comment by tonyahowe** [comment]
Seems to be fixed! Thanks!
