### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#343]
The reset password functionality doesn't work--I don't think we collect passwords, so resetting is impossible now?

**Comment by wsalesky** [comment]
@tonyahowe This is what I used to reset your password on the production site. It should work for both.

**Comment by tonyahowe** [comment]
The same password? How do I get the temp password, if not thru email? Sorry, just confused.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wsalesky** [comment]
Is this still an issue?

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 @cruotolo This has been resolved
