### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by jobrien62** [LiteratureInContext/LiC-app#344]
there are a couple of texts with tables. The one I'm working on now is Robinson Crusoe, which has a table that is on pages 76-77. I've coded the table in TEI (I think)--how can we get it to display? I attach a screenshot to show how it is formatted in the original.
<img width="485" alt="Screenshot 2024-08-14 at 3 39 25 PM" src="https://github.com/user-attachments/assets/a0ed5aa5-d9e3-482a-9baa-a39fef419401">

**Comment by jobrien62** [comment]
That would be great. Thank you!

From: Winona Salesky ***@***.***>
Date: Wednesday, August 14, 2024 at 8:45 PM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] tables (Issue #344)

@jobrien62<https://github.com/jobrien62> I probably need to add styles for tables into the xquery. Should be an easy fix.

**Comment by wsalesky** [comment]
Fixed

**Comment by jobrien62** [comment]
Perfect!

From: Winona Salesky ***@***.***>
Date: Thursday, August 15, 2024 at 9:26 AM
To: LiteratureInContext/LiC-app ***@***.***>
Cc: O'Brien, John F (jo6p) ***@***.***>, Mention ***@***.***>
Subject: Re: [LiteratureInContext/LiC-app] tables (Issue #344)

Fixed
