### ISSUE TITLE
Problem downloading epub and pdf on one text

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#356]
When trying to download the pdf or epub (on the Prod site) of THE FEMALE AMERICAN by Winkfield, we get errors:

pdf download error: 
![Screenshot 2024-09-04 151029](https://github.com/user-attachments/assets/d2fce4ca-02eb-425c-a098-484eb0ca5e6d)

epub download error:
![Screenshot 2024-09-04 151053](https://github.com/user-attachments/assets/b6e0a8c5-59ec-47d8-8878-c24cb8e6f214)

**Comment by wsalesky** [comment]
@tonyahowe There is a duplicate id in the the record. Do a search for id="consign

All id's must be unique. I also fixed a bug in the epub code. Once the id is corrected it should be fine.
