### ISSUE TITLE
Pages to ignore?

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#36]
In LiC-data, we currently have pages like **editors.xml** and **template.xml** that are showing up, as one would expect, in the list of data; is it possible to create a folder in LiC-data, called something like "ignore" or "commonFiles"--something that would make sense--into which we could put things like editors.xm and the templates we create, so that they _don't_ appear in the regular list of files? Or is it better to do that with templates rather than editors.xml? Or in some other way? We will eventually have personography xml files for each author, which will include broader introductory information, and those should not appear with the regular texts (they would be subordinate to or otherwise associated with the regular texts, called up individually). For instance, a wollstonecraft.xml file that would contain a headnote for Wollstonecraft. We could create three folders to ignore on regular display, one for headnotes, one for templates, and one for data like that in editors.xml. I'm not sure what the best solution would be here.

**Comment by wsalesky** [comment]
Just move them out of LiC-data/data. You could move them to LiC-data/templates for example. Moving editors will break the current script, but it is an easy fix and better to do it now than later, just don't be alarmed when the contributors page breaks.

**Comment by tonyahowe** [comment]
Okay--I created three folders in LiC-data: templates, contributors, and headnotes.

**Comment by wsalesky** [comment]
@tonyahowe Ops, I just looked at this. Anything you do not want showing up in the search should be above the LiC-data/data directory. So move them to: 

- LiC-data/templates
- LiC-data/contributors

I don't know about headnotes, those you may want to be able to search? 


-

**Comment by tonyahowe** [comment]
Yes, the headnotes will be something we'd like to be able to search; these we have not figured out how we want to do, but they should be associated with and yet separate from the texts themselves. I'm not sure how to do this; this may be something for a fuller conversation! I will move the templates and contributors folders!

**Comment by tonyahowe** [comment]
It looks like there's already a "templates" folder in LiC-data. I'll still move it, but rename it "fileTemplates."

**Comment by tonyahowe** [comment]
Okay-- I moved the folders, which of course broke the contributors links.

**Comment by wsalesky** [comment]
Fixed.
