### ISSUE TITLE
Login problems (redux)

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#361]
There still seem to be intermittent login problems; this from a user:

"FYI, I am having the same issue I had a couple of months ago, which I'm not sure whether I reported - when I try to log in to the site, I just get redirected to the homepage but not logged in. So I can't actually access the coursepack functionality at this time. I did manage to use it once before, when filling out the survey you sent me, but not since then."

Part of that may be signage and feedback; what happened that the user wasn't logged in? Was the password incorrect? 

Also, I will post this in another issue related to the coursepack issue, but it may have login implications, too. When I log in (after much effort, including some password resets--I wonder if there's a way to let people view their passwords as they're typed?), I try to save a selection to a coursepack I created, but no luck. This is the same in dev and prod. I "need to be logged in to save"; see video here: 

https://github.com/user-attachments/assets/22d2b92e-e2a4-48da-a795-7163ff058065

Finally, I think that sometimes, the first time one tries to log in, it fails silently (even though it's the right password; I have mine now set up in my password manager), but then trying again succeeds. I'll try to capture video of this, but so far it's just my word! :)

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 @cruotolo Can this feature be retested. It should be fixed, but I need verification. Thanks!

**Comment by tonyahowe** [comment]
The "need to be logged in to save" issue has been fixed! :)
