### ISSUE TITLE
Slow Running

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#42]
Hi, Winona! The site seems to be loading and moving very slowly (the dev site, not the production site). Is it something to do with github? Not sure, but sometimes the slowness times it out or throws a 502. On refresh, it comes back, but slowly.

**Comment by wsalesky** [comment]
I will check with Dave. I think there is a memory leak in the version of eXist we are using. I'm expecting a new release anytime. But maybe there is something he can do to free up some memory while we wait.

**Comment by tonyahowe** [comment]
Seems to be working nicely now!
