### ISSUE TITLE
Image Display

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#44]
Problem: Page display quickly outpaces/doesn't match up with text; how to get a true/better "facing page" display?

**Comment by tonyahowe** [comment]
Not really a question, but we are thinking about options. Smaller page images that expand? Page images tied to placement of <pb>?

**Comment by wsalesky** [comment]
A few options: 
1. Smaller images
2. Constrain the HTML display to align the text div and the page image. 
3. A side by side image/page interface, example: http://141.40.254.7:8080/exist/apps/usaybia/text/1?page=PB2.240. This forces a 1 page at a time interface, which is speedy for large texts, but also annoying for users who prefer to see larger chunks of content. 
4. Some combination of the above, with the option to 'toggle' the view an get full text, or text and images. etc.

**Comment by tonyahowe** [comment]
I think we are leaning toward option 2, but it would be interesting to see a toggle option--full text + aligned page images (option 2), and side-by-side/page-by-page (your option 3).

**Comment by wsalesky** [comment]
Okay, I will look into it.

**Comment by wsalesky** [comment]
@tonyahowe  Okay, I added option 2. What do you think?

**Comment by tonyahowe** [comment]
That looks good! Would it be possible to toggle between 1.) this, and 2.) with/without the page images? 

Related note: It seems however that now the images in notes aren't showing up (see the first note in franklin-autobiography.xml as an example). I don't know if this was an effect of the recent update?

**Comment by wsalesky** [comment]
Fixed.

**Comment by tonyahowe** [comment]
@wsalesky: can we add a toggle feature to make different displays possible? We are hoping to toggle between the text only and text + page images.

**Comment by wsalesky** [comment]
@tonyahowe Sure. What should be the default view? Text only?

**Comment by tonyahowe** [comment]
I am inclined toward text only. @jobrien62 what are your thoughts? Text only on initial view might be cleaner. Would we be able to shrink the size of the images, as well? They are still quite large, and there's lots of empty space between the text transcription. Let's wait until @jobrien62 weighs in, but does this seem pretty simple?

**Comment by jobrien62** [comment]
So, the idea would be text-only as the default view, with, then, the option to toggle to a view with text + page images?
________________________________

**Comment by tonyahowe** [comment]
That’s right—the extra space between the text blocks, to accommodate the page images, seems distracting to me, as I look at it more. I’m not wedded to this, but if it seems like a good idea, we might try it.

**Comment by jobrien62** [comment]
Yes, I can see that. It's a helpful feature for one kind of reading, and a kind of reading that we want to support. But if a reader simply wants to get on with it, it's distracting, so having a straight-text view as the default with the option to switch to a text + page image view makes sense. John
________________________________

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 Added. Let me know what you think.

**Comment by tonyahowe** [comment]
I love it!
