### ISSUE TITLE
Coursepack EPUB not working

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#48]
Doesn't seem to be able to download/open as EPUB

**Comment by wsalesky** [comment]
@tonyahowe Sorry I think I just did a copy and paste of Joe's code on this module. I will take a closer look and see if we can get it working correctly. It may take a few hours.

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 I think this has also been fixed?
