### ISSUE TITLE
Weird bug in faceting authors

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#54]
Hi, Winona! A weird bug has raised its head--or maybe I just noticed it. When we go to the browse/search page, you'll note that Franklin has authored 40 texts. I'm not sure why this is--the word Franklin is nowhere in the XML files that return, which include a lot of Wheatley. 

This might be related to the multiple Philips, Katherine entries in the author list, as well--we've looked through the data and cannot find any likely culprits, though of course we may have missed it. But I figured I'd put it on your radar!

![Screen Shot 2019-05-28 at 10 31 27 AM](https://user-images.githubusercontent.com/1153464/58486603-24f79a80-8134-11e9-9087-038210938283.png)

**Comment by wsalesky** [comment]
@tonyahowe mystery solved. The Author facets lookup authors by their key and then only prints the first name in the group, in this case the first name is Benjamin Franklin even though all the other names are actually Phillis Wheatley. This is because this file: https://github.com/LiteratureInContext/LiC-data/blob/development/data/Franklin/franklin-autobiography.xml#L8

is using the same author key as for Benjamin Franklin as is used for Phillis Wheatley (n50016726). I'm guessing the Benjamin Franklin key is the incorrect key, once it is changed you will have 39 Phillis Wheatley works and one Benjamin Franklin work. 

Let me know if that does not solve the problem.

**Comment by tonyahowe** [comment]
Yes!! That’s it! I will correct that ASAP.

**Comment by tonyahowe** [comment]
That was the problem! We will probably need to change something to avoid this kind of problem--if we draw the author information from one place only, in sourceDesc OR the fileDesc, then we can cut down on problems. I didn't foresee this! @jobrien62 do you have a preference? Should we pull the author information from the first mention, in the fileDesc, or from the broader info re: sources in sourceDesc? We should pick one, and only put the lcnaf key there.

**Comment by jobrien62** [comment]
No strong preference on my end, though I think that fileDesc probably makes the most sense, as the more general category.

**Comment by tonyahowe** [comment]
@wsalesky I think in order to eliminate confusion down the line, we should only pull the author information from one place--the fileDesc/author element, as here from rochester-satire-mankind.xml:

`            <author>
               <persName type="lcnaf" key="n79027135">
                  
                  <name> 
                     <forename>John</forename>
                     <surname>Wilmot</surname>
                     <addName>Earl of Rochester</addName>
                  </name>
               </persName>
            </author>`

Note that some authors, like this one, will also have additional names--can we alphabetize as normal by surname, but include any addNames after? For instance, "Wilmot, John, Earl of Rochester" for bibliographic purposes, but "John Wilmot, Earl of Rochester" for display purposes?

**Comment by tonyahowe** [comment]
@wsalesky @jobrien62  I've removed all the lcnaf keys from the second instance of `<author>` -- the site seems fine, so it's the difference between the first and second keys that causes confusion. As long as we keep the key ONLY in the first instance of `<author>` we should be good!

**Comment by wsalesky** [comment]
@tonyahowe @jobrien62 Sounds good. Should we close this or leave it open for reference?

**Comment by jobrien62** [comment]
Yes let's close.
________________________________
