### ISSUE TITLE
Links in "source texts" expansion not working

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#59]
Hi, Winona-- I think we already talked about this, but I can't find the issue. At any rate, the links to live URLs used in the sourceDesc and imprint elements of the XML aren't rendering as links in the Source Texts expansion. Here's an image--see that XML for examples:

<img width="1191" alt="Screen Shot 2019-06-06 at 10 45 28 AM" src="https://user-images.githubusercontent.com/1153464/59042622-cb385400-8848-11e9-860d-57c1d58fd636.png">

**Comment by wsalesky** [comment]
Fixed.
