### ISSUE TITLE
addNames

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#60]
Note that some authors, like this one, will also have additional names--can we alphabetize as normal by surname, but include any addNames after? For instance, "Wilmot, John, Earl of Rochester" for bibliographic purposes, but "John Wilmot, Earl of Rochester" for display purposes? Here is a sample from rochester-satire-mankind.xml:

`            <author>
               <persName type="lcnaf" key="n79027135">
                  
                  <name> 
                     <forename>John</forename>
                     <surname>Wilmot</surname>
                     <addName>Earl of Rochester</addName>
                  </name>
               </persName>
            </author>`

**Comment by wsalesky** [comment]
Done. @tonyahowe if the display looks good please close this issue.

**Comment by wsalesky** [comment]
@tonyahowe can this be closed?

**Comment by tonyahowe** [comment]
Sorry for the delay! This looks good, except there's weird spacing on the main document display--seems to be an extra space before the , addName: https://anthologydev.lib.virginia.edu/work/Rochester/rochester-satyr-mankind
