### ISSUE TITLE
Minor display issue: head type="title"

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#64]
@wsalesky when the page image toggle is on, the formatting of the `<head type="title">` element changes--it becomes smaller, seemingly exactly like the regular text font. Can we make that display in the same size as the `<head type="title">` when the page image toggle is off?

**Comment by wsalesky** [comment]
I will take a look.

**Comment by wsalesky** [comment]
@tonyahowe can you link to an example record?

**Comment by tonyahowe** [comment]
All of them—any one will do! 😊

**Comment by wsalesky** [comment]
fixed
