### ISSUE TITLE
Mobile display

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#66]
Mobile display is pretty smooshed... can we alter anything there to make it a little more friendly? Not sure how complicated that is?

**Comment by wsalesky** [comment]
@tonyahowe has this been resolved? Do you want me to do any additional work? Are there specific problem areas?

**Comment by tonyahowe** [comment]
I think it's been resolved; the splash page with the scrolling feature is a bit wonky on mobile when displaying images, though. I wonder if we could resize any images to be a %? Otherwise, the text looks good!

**Comment by wsalesky** [comment]
@tonyahowe  I will look into the homepage.

**Comment by wsalesky** [comment]
Fixed
