### ISSUE TITLE
Search tool in browse

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#7]
The search tool in browse is a little counter-intuitive to use, because of the shared blue color of the search icon and the “create new coursepack” button. Can we have a “search” button beside the “include annotations” checkbox, and then have the coursepack creation features in a place of their own?

**Comment by wsalesky** [comment]
This has been resolved by moving the coursepack functions out of the search box. @tonyahowe @jobrien62 you may close this if you like the new structure. Otherwise, add comments below.

**Comment by jobrien62** [comment]
OK by me
!

**Comment by tonyahowe** [comment]
This is a little issue, but can we change the text of "create new coursepack" to "create coursepack from selected"? and "add selected to coursepack"? Or is it just me? :-/

**Comment by wsalesky** [comment]
Done. It makes the buttons a little longer, which could be problematic on smaller screens, but we can adjust if it becomes an issue.
