### ISSUE TITLE
Keyword search

### ISSUE THREAD

**Issue by wsalesky** [LiteratureInContext/LiC-app#8]
Searching: the keyword search (both the top most search bar and the more specific one on the right hand of the browse page) doesn’t find authors--for instance, doing a keyword search for “finch” returns nothing. Shouldn’t it return for authors, too? Or no?

**Comment by wsalesky** [comment]
Fixed on dev. @tonyahowe @jobrien62 please check.

**Comment by cruotolo** [comment]
Working now for me on dev.

**Comment by jobrien62** [comment]
me too
