### ISSUE TITLE
Multiple authors--browse view

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#82]
Related to issue #81 -- in the browse list (or search results list), texts with multiple authors should display all authors. See [https://anthologydev.lib.virginia.edu/search.html?query=j.+b.&field=keyword](https://anthologydev.lib.virginia.edu/search.html?query=j.+b.&field=keyword), or search for "rebus" by Wheatley and J. B..

**Comment by wsalesky** [comment]
Fixed.
