### ISSUE TITLE
Coursepack feature

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#92]
Can we add highlighted/selected text from long XML files to a coursepack, to display as full documents are now displayed?

**Comment by wsalesky** [comment]
@tonyahowe I assume you would want to save the underlying xml to the coursepack? Or just the text?

**Comment by tonyahowe** [comment]
Yes, the same way whole texts are added.

**Comment by wsalesky** [comment]
Same as #110
