### ISSUE TITLE
Hypothesis feature

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-app#93]
We'd like to enable hypothes.is on LiC natively (instead of the plugin that individuals can add) so we can have user-contributed hypothesis notes, as well as editor/student-contributed XML annotations. A more complicated feature is potentially using hypothesis to gather user-submitted annotations. Perhaps tag those intended as submissions to become official annotations? Or even better, find some way to pull them into a hopper of sorts on our server, to be inserted into the XML? I have no idea how that would work or what's possible, but the goal is to enable contribution to the XML database.

**Comment by wsalesky** [comment]
@tonyahowe Added to development site. If approved I will move to master.

**Comment by tonyahowe** [comment]
Yes, this looks great--I've been playing around with it already! THANKS!

**Comment by wsalesky** [comment]
@wsalesky add to master
